/// Flutter icons Kinarian
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kinarian
///      fonts:
///       - asset: fonts/Kinarian.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Kinarian {
  Kinarian._();

  static const _kFontFam = 'Kinarian';

  static const IconData gedung_pernikahan = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData gridmenu = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData listmenu = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData magnifying_glass = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData souvenir = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData call = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData domain = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData coin = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData speech_bubble = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData whatsapp = const IconData(0xf232, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf30c, fontFamily: _kFontFam);
}
